/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all people */
        get: operations["listPeople"];
        put?: never;
        /** Add a person */
        post: operations["createPerson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all expenses, most recent first */
        get: operations["listExpenses"];
        put?: never;
        /** Add an expense, split equally among participant_ids */
        post: operations["createExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/{expense_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit an expense (full replace) */
        put: operations["replaceExpense"];
        post?: never;
        /** Delete an expense */
        delete: operations["deleteExpense"];
        options?: never;
        head?: never;
        /** Partially edit an expense */
        patch: operations["updateExpense"];
        trace?: never;
    };
    "/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Each person's net position */
        get: operations["listBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Person: {
            readonly id: number;
            name: string;
        };
        PersonCreate: {
            name: string;
        };
        Expense: {
            readonly id: number;
            description: string;
            /** @description Currency amount, rounded to 2 decimal places. */
            amount: number;
            payer_id: number;
            /** Format: date */
            date: string;
            participant_ids: number[];
        };
        ExpenseWrite: {
            description: string;
            /** @description Currency amount, rounded to 2 decimal places. */
            amount: number;
            payer_id: number;
            /** Format: date */
            date: string;
            participant_ids: number[];
        };
        ExpensePatch: {
            description?: string;
            /** @description Currency amount, rounded to 2 decimal places. */
            amount?: number;
            payer_id?: number;
            /** Format: date */
            date?: string;
            participant_ids?: number[];
        };
        Balance: {
            person_id: number;
            name: string;
            balance: number;
        };
        Error: {
            detail: string;
        };
        HTTPValidationError: {
            detail: {
                loc: (string | number)[];
                msg: string;
                type: string;
            }[];
        };
    };
    responses: never;
    parameters: {
        ExpenseId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPeople: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All people, ordered by id ascending (insertion order) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"][];
                };
            };
        };
    };
    createPerson: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonCreate"];
            };
        };
        responses: {
            /** @description Person created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listExpenses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All expenses, ordered by date descending, then id descending as a tiebreak for same-date expenses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"][];
                };
            };
        };
    };
    createExpense: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseWrite"];
            };
        };
        responses: {
            /** @description Expense created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            /** @description payer_id or an entry in participant_ids does not match an existing person */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replaceExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseWrite"];
            };
        };
        responses: {
            /** @description Expense updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            /** @description payer_id or an entry in participant_ids does not match an existing person */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description expense_id does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Expense deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description expense_id does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpensePatch"];
            };
        };
        responses: {
            /** @description Expense updated (full resource returned, same as PUT); an empty request body ({}) is valid and is a no-op update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            /** @description payer_id or an entry in participant_ids does not match an existing person (only checked for fields present in the body) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description expense_id does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation error (only applied to fields present in the body) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listBalances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per person currently in the group (including people with zero expenses), ordered by person_id ascending. Positive balance means net owed to them; negative means they net owe; 0 means settled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Balance"][];
                };
            };
        };
    };
}
